apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: serviduino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        envFrom:
          - configMapRef:
              name: serviduino-config
          - secretRef:
              name: serviduino-secrets
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq  # Directorio de datos de RabbitMQ
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-data  # Refiere al PVC creado previamente
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: serviduino  # Namespace actualizado
spec:
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  namespace: serviduino
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: akane.benlop27.com
    http:
      paths:
      - path: /rabbitmq
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              number: 15672
