name: Publicar Artefacto FrontEnd

on:
  release:
    types:
      - created  # Este evento se ejecuta cuando se crea un nuevo release
  workflow_dispatch: 
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Chequear el código
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar Docker para usar los secretos de Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Paso 3: Construir la imagen Docker
    - name: Build the Docker image
      run: |
        # Usar el nombre de la versión del release como etiqueta
        VERSION=${{ github.event.release.tag_name }}
        cd frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/serviduino-ui:latest .

    # Paso 4: Empujar la imagen al Docker Hub
    - name: Push the Docker image
      run: |
        VERSION=${{ github.event.release.tag_name }}
        docker push ${{ secrets.DOCKER_USERNAME }}/serviduino-ui:latest

    # Paso 5: Limpiar las imágenes locales
    - name: Remove local images
      run: |
        VERSION=${{ github.event.release.tag_name }}
        docker rmi ${{ secrets.DOCKER_USERNAME }}/serviduino-ui:$VERSION
